apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-04-04T04:13:01Z"
  generation: 1
  labels:
    app: web-003
  name: web-003
  namespace: default
  resourceVersion: "50471"
  uid: 2e8c35c2-8fe1-4cf4-98cf-344aa9a4a6b5
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web-003
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-003
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
