apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2023-04-03T11:55:36Z"
  generation: 1
  labels:
    app: web-proj-268
  name: web-proj-268
  namespace: default
  resourceVersion: "42836"
  uid: 55d44aaf-d513-4823-978a-671979b0990a
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: web-proj-268
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-proj-268
    spec:
      containers:
      - image: nginx:1.16
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
