apiVersion: v1
kind: Pod
metadata:
  labels:
    run: prod-nginx
  name: prod-nginx
spec:
  containers:
    - image: nginx
      name: prod-nginx
  tolerations :
    - key : "env_type"
      operator : "Equal"
      value : "production"
      effect : "NoSchedule"